---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Generate federation test user1 cloudrc file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/ci-framework-data/tmp/{{ cifmw_federation_keycloak_testuser1_username }}rc"
    content: |
      unset OS_CLOUD
      export OS_CACERT=/home/cloud-admin/sso-service-ca.crt
      export OS_PROJECT_NAME="{{ cifmw_federation_project_name }}"
      export OS_PROJECT_DOMAIN_NAME="{{ cifmw_federation_domain }}"
      export OS_AUTH_URL="{{ cifmw_federation_keystone_url }}/v3"
      export OS_IDENTITY_API_VERSION=3
      export OS_AUTH_PLUGIN=openid
      export OS_AUTH_TYPE=v3oidcpassword
      export OS_USERNAME="{{ cifmw_federation_keycloak_testuser1_username }}"
      export OS_PASSWORD="{{ cifmw_federation_keycloak_testuser1_password }}"
      export OS_IDENTITY_PROVIDER="{{ cifmw_federation_IdpName }}"
      export OS_CLIENT_ID="{{ cifmw_federation_keycloak_client_id }}"
      export OS_CLIENT_SECRET="{{ cifmw_federation_keycloak_client_secret }}"
      export OS_OPENID_SCOPE="openid profile email"
      export OS_PROTOCOL=openid
      export OS_ACCESS_TOKEN_TYPE=access_token
      export OS_DISCOVERY_ENDPOINT="{{ cifmw_federation_keycloak_url }}/.well-known/openid-configuration"

- name: Copy federation test user1 cloudrc file into pod
  kubernetes.core.k8s_cp:
    namespace: "{{ cifmw_federation_run_osp_cmd_namespace }}"
    pod: openstackclient
    remote_path: "/home/cloud-admin/{{ cifmw_federation_keycloak_testuser1_username }}rc"
    local_path: "{{ ansible_user_dir }}/ci-framework-data/tmp/{{ cifmw_federation_keycloak_testuser1_username }}rc"

- name: Copy SSO CA file into openstackclient pod
  kubernetes.core.k8s_cp:
    namespace: "{{ cifmw_federation_run_osp_cmd_namespace }}"
    pod: openstackclient
    remote_path: "/home/cloud-admin/sso-service-ca.crt"
    local_path: "{{ ansible_user_dir }}/ci-framework-data/tmp/sso-service-ca.crt"

- name: Get testuser1 token
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.command:
    cmd: >-
      oc rsh openstackclient
      source /home/cloud-admin/{{ cifmw_federation_keycloak_testuser1_username }}rc
      openstack token issue -f yaml
  register: federation_sso_testuser1_token
